sonar.projectKey=Sanctum-Inc_cms-react
sonar.organization=sanctum-inc

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.*,**/cypress/**

sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/cypress/**,**/*.config.*,src/main.tsx, src/api