/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AddCourtCaseDateRequest } from './models/AddCourtCaseDateRequest';
export type { AddCourtCaseRequest } from './models/AddCourtCaseRequest';
export type { AddEmailRequest } from './models/AddEmailRequest';
export type { AddFirmRequest } from './models/AddFirmRequest';
export type { AddInvoiceItemRequest } from './models/AddInvoiceItemRequest';
export type { AddInvoiceRequest } from './models/AddInvoiceRequest';
export type { AddLawyerRequest } from './models/AddLawyerRequest';
export type { CourtCaseDateItemResponse } from './models/CourtCaseDateItemResponse';
export type { CourtCaseDateResponse } from './models/CourtCaseDateResponse';
export type { CourtCaseDateTypes } from './models/CourtCaseDateTypes';
export type { CourtCaseInformationQueryDatesResult } from './models/CourtCaseInformationQueryDatesResult';
export type { CourtCaseInformationQueryDocumentsResult } from './models/CourtCaseInformationQueryDocumentsResult';
export type { CourtCaseInformationQueryInvoicesResult } from './models/CourtCaseInformationQueryInvoicesResult';
export type { CourtCaseInformationQueryLawyersResult } from './models/CourtCaseInformationQueryLawyersResult';
export type { CourtCaseInformationResult } from './models/CourtCaseInformationResult';
export type { CourtCaseNumberResponse } from './models/CourtCaseNumberResponse';
export type { CourtCaseOutcomes } from './models/CourtCaseOutcomes';
export type { CourtCaseResponse } from './models/CourtCaseResponse';
export type { CourtCaseStatus } from './models/CourtCaseStatus';
export type { CourtCaseTypes } from './models/CourtCaseTypes';
export type { DashBoardResult } from './models/DashBoardResult';
export type { DocumentResponse } from './models/DocumentResponse';
export type { EmailResponse } from './models/EmailResponse';
export type { EmailStatus } from './models/EmailStatus';
export type { EntityTagHeaderValue } from './models/EntityTagHeaderValue';
export type { FileResult } from './models/FileResult';
export type { FileStreamResult } from './models/FileStreamResult';
export type { FirmResponse } from './models/FirmResponse';
export type { InvoiceItemResponse } from './models/InvoiceItemResponse';
export type { InvoiceNumberResponse } from './models/InvoiceNumberResponse';
export type { InvoiceResponse } from './models/InvoiceResponse';
export type { InvoiceStatus } from './models/InvoiceStatus';
export type { LawyerReportActivityLogResponse } from './models/LawyerReportActivityLogResponse';
export type { LawyerReportCardsResponse } from './models/LawyerReportCardsResponse';
export type { LawyerReportCaseDistributionResponse } from './models/LawyerReportCaseDistributionResponse';
export type { LawyerReportInvoicesResponse } from './models/LawyerReportInvoicesResponse';
export type { LawyerReportResponse } from './models/LawyerReportResponse';
export type { LawyerReportUpcomingDeadlinesResponse } from './models/LawyerReportUpcomingDeadlinesResponse';
export type { LawyerResponse } from './models/LawyerResponse';
export type { LoginRequest } from './models/LoginRequest';
export type { LoginResponse } from './models/LoginResponse';
export type { ProblemDetails } from './models/ProblemDetails';
export type { RecentCaseActivityResult } from './models/RecentCaseActivityResult';
export type { RegisterRequest } from './models/RegisterRequest';
export type { Speciality } from './models/Speciality';
export type { Stream } from './models/Stream';
export type { StringSegment } from './models/StringSegment';
export type { UpcomingCourtCaseActivityResult } from './models/UpcomingCourtCaseActivityResult';
export type { UpdateCourtCaseDateRequest } from './models/UpdateCourtCaseDateRequest';
export type { UpdateCourtCaseRequest } from './models/UpdateCourtCaseRequest';
export type { UpdateDocumentRequest } from './models/UpdateDocumentRequest';
export type { UpdateFirmRequest } from './models/UpdateFirmRequest';
export type { UpdateInvoiceItemRequest } from './models/UpdateInvoiceItemRequest';
export type { UpdateInvoiceRequest } from './models/UpdateInvoiceRequest';
export type { UpdateInvoiceStatusRequest } from './models/UpdateInvoiceStatusRequest';
export type { UpdateLawyerRequest } from './models/UpdateLawyerRequest';

export { CourtCaseService } from './services/CourtCaseService';
export { CourtCaseDateService } from './services/CourtCaseDateService';
export { DashboardService } from './services/DashboardService';
export { DocumentService } from './services/DocumentService';
export { EmailService } from './services/EmailService';
export { FirmService } from './services/FirmService';
export { InvoiceService } from './services/InvoiceService';
export { InvoiceItemService } from './services/InvoiceItemService';
export { LawyerService } from './services/LawyerService';
export { UserService } from './services/UserService';
